name: poc_pdf_creation
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6
  pdf: ^3.11.0
  printing: ^5.13.1
  path_provider: ^2.1.3
  intl: ^0.19.0
  cpf_cnpj_validator: ^2.0.0
  faker: ^2.2.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/roboto/
    - assets/fonts/material_icons/
  fonts:
    - family: Arial
      fonts:
        - asset: assets/fonts/roboto/Roboto-Regular.ttf
          weight: 400
    - family: Arial
      fonts:
        - asset: assets/fonts/material_icons/MaterialIcons-Regular.ttf
          weight: 400
  
